services:
  myplants:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: myplants-api
    container_name: myplants-api
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT
      - MONGO_URI
      - GEMINI_API_KEY
      - GEMINI_MODEL
      - EMAIL_USER
      - EMAIL_PASS
      - API_URL
      - TZ
      - FIREBASE_SERVICE_ACCOUNT
    volumes:
      - ./api/public/uploads:/app/public/uploads


    networks:
      - myplants-network

networks:
  myplants-network:
    external: true