services:
  myplants:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: myplants-api
    container_name: myplants-api
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - MONGO_URI="${MONGO_URI}"
      - GEMINI_API_KEY="${GEMINI_API_KEY}"
      - GEMINI_MODEL="${GEMINI_MODEL}"
      - EMAIL_USER="${EMAIL_USER}"
      - EMAIL_PASS="${EMAIL_PASS}"
      - API_URL="${API_URL}"
      - TZ="${TZ}"
      - FIREBASE_SERVICE_ACCOUNT="${FIREBASE_SERVICE_ACCOUNT}"
    networks:
      - myplants-network

networks:
  myplants-network:
    external: true